# frontend nginx configuration

server {
    listen 80;
    root /usr/share/nginx/html;
    # The default file to look for
    index index.html;

    # multi page routing is handled from within react
    location / {
        try_files $uri $uri/ /index.html;
    }

    # This location block handles all API requests.
    # Any request starting with /api/ will be proxied.
    location /api/ {
        # Forward the request to our backend service.
        # 'backend' is the service name from docker-compose.yml.
        # '5000' is the port the backend service listens on.
        proxy_pass http://backend:5000;

        # These headers are important for passing along
        # the original request information to the backend.
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}